### ISSUE TITLE
[BE] RestAPI 정리 및 세팅 - Swagger

### ISSUE THREAD

**Issue by harvartz** [kinopioB/EatGo-Backend#4]
## Feature Description
- RestAPI 정리 및 세팅

## Todo list

- [ ] RestAPI 정리 및 세팅

**Comment by SeungJooKim** [comment]
@GetMapping("reviews")
public ResponseEntity<List<ReviewDto>> getAllReviews() 
이건...안필요할 거 같은데..? 어디에 쓸 건지! 알려주세용~:) 

@PostMapping("/{storeId}/reviews")
얘 처럼 앞에 / 붙이는 걸로 통일!!! 해주면 좋을거 같아욥

``

	@PostMapping("/{storeId}/reviews")
	public ResponseEntity<Integer> createReview(@PathVariable int storeId, ReviewDto reviewDto){		
		
		reviewDto.setStoreId(storeId);
 		int result = storeService.createReview(reviewDto); 
		return new ResponseEntity<Integer>(result, HttpStatus.ACCEPTED);
	}
``
여기서 insert 실패했을 시에 리턴값이 저거면 안될거 같아요! 이것도 처리해주면 좋을듯!
아 그리고  ResponseEntity Integer  보다 ResponseEntity Boolean 이 좋지 않을까..하는 개인적인 생각?ㅋㅋㅋㅋ

**Comment by SeungJooKim** [comment]
변수명에 자료형이 들어가는 거는 피하는 게 좋다구해용!
- https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/ 
이거 참고하면 좋을 듯 싶숩니다!

VO / DTO 에서 변수 wrapper 클래스 사용을 권장하는 거 같음! 아래 링크 참고!
- https://velog.io/@power0080/Wrapper-%ED%81%B4%EB%9E%98%EC%8A%A4%EC%99%80-%EA%B8%B0%EB%B3%B8%ED%83%80%EC%9E%85

**Comment by SeungJooKim** [comment]
HttpStatus.ACCEPTED ? 이걸 사용한 이유는???
Accepted 는 요청이 성공적으로 들어왔지만 아직 해당 요청에 대해 처리 중이라는 뜻으로 알고있는뎅!
